### ISSUE TITLE
New MusicBrainz releases not showing up

### ISSUE THREAD

**Issue by ToadKing** [gchudov/db.cue.tools#20]
Example: http://db.cue.tools/top.php?tocid=ctvjFPq3N6GF0IdVCrEPTlr51iI-

This CD is linked to a MusicBrainz album but the site isn't picking up on it. MB did have a DB schema change recently that might be part of the issue: https://blog.metabrainz.org/2022/05/16/musicbrainz-schema-change-release-2022-05-16-with-upgrade-instructions/

**Comment by ha-korth** [comment]
This still does not seem to be fixed (or there was a newer change that stopped updates again).

**Comment by ToadKing** [comment]
MB releases appear to be showing up again.
