### ISSUE TITLE
Latest MusicBrainz metadata not fetched by CTDB

### ISSUE THREAD

**Issue by eprillios** [gchudov/db.cue.tools#21]
As advised by @ha-korth in https://github.com/gchudov/cuetools.net/issues/293#issuecomment-1680333233 I am cross-submitting the following issue in this repository.

---

Thanks for this amazing set of software! I have started ripping CDs again using CUERipper, and it works splendidly and hassle-free.

I've come to notice that my latest additions (e.g. for when a disc was previously unknown) to the MusicBrainz database are not reflected in the metadata fetched by CUERipper from CTDB. Waiting for a week has not changed this issue.

I've read that a schema change on the end of MusicBrainz could be the culprit. [This topic on Hydrogenaudio](https://hydrogenaud.io/index.php/topic,124593/) describes problems similar to what I am experiencing.

Please let me know if I can be of any help providing further details.

**Comment by gchudov** [comment]
Thanks, update is now in progress

**Comment by gchudov** [comment]
Should be in sync now
